name: Swift CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    strategy:
      matrix:
        xcode-version: ["14.3", "15.0"]
        swift-version: ["5.8", "5.9"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Xcode ${{ matrix.xcode-version }}
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode-version }}.app/Contents/Developer

    - name: Set up Swift ${{ matrix.swift-version }}
      run: swift --version

    - name: Install Dependencies
      run: swift package resolve

    - name: Build Project
      run: swift build --enable-test-discovery

    - name: Run Tests
      run: swift test --enable-test-discovery
